export default {
  words: [
    {
      category: "transportations",
      list: [
        "Car",
        "Motorcycle",
        "Bicycle",
        "Bus",
        "Truck",
        "Van",
        "Taxi",
        "Ambulance",
        "Police Car",
        "Fire Truck",
        "Train",
        "Subway",
        "Tram",
        "Helicopter",
        "Airplane",
        "Jet",
        "Hot Air Balloon",
        "Blimp",
        "Drone",
        "Rocket",
        "Boat",
        "Ship",
        "Yacht",
        "Submarine",
        "Canoe",
        "Kayak",
        "Ferry",
        "Jet Ski",
        "Cruise Ship",
        "Speedboat",
        "Sailboat",
        "Tractor",
        "Bulldozer",
        "Excavator",
        "Crane",
        "Forklift",
        "Dump Truck",
        "Cement Mixer",
        "Garbage Truck",
        "Tow Truck",
        "Scooter",
        "Skateboard",
        "Segway",
        "Golf Cart",
        "Snowmobile",
        "Sleigh",
        "Rickshaw",
        "Tuk-tuk",
        "Gondola",
        "Hovercraft",
        "Space Shuttle",
        "Glider",
        "Zeppelin",
        "Limousine",
        "Convertible",
        "SUV",
        "Pickup Truck",
        "Minivan",
        "Campervan",
        "RV",
        "Double-decker Bus",
        "School Bus",
        "Trolley",
        "Cable Car",
        "Funicular",
        "Monorail",
        "Tank",
        "Jeep",
        "Hearse",
        "Mail Truck",
        "Food Truck",
        "Barge",
        "Trawler",
        "Catamaran",
        "Dinghy",
        "Raft",
        "Unicycle",
        "Tricycle",
      ],
    },
    {
      category: "fruits",
      list: [
        "Apple",
        "Banana",
        "Orange",
        "Grape",
        "Strawberry",
        "Mango",
        "Pineapple",
        "Watermelon",
        "Lemon",
        "Lime",
        "Peach",
        "Cherry",
        "Pear",
        "Plum",
        "Kiwi",
        "Blueberry",
        "Raspberry",
        "Blackberry",
        "Avocado",
        "Papaya",
        "Coconut",
        "Pomegranate",
        "Dragon Fruit",
        "Grapefruit",
        "Apricot",
        "Nectarine",
        "Cantaloupe",
        "Honeydew",
        "Fig",
        "Date",
        "Lychee",
        "Durian",
        "Jackfruit",
        "Guava",
        "Passion Fruit",
        "Star Fruit",
        "Mangosteen",
        "Rambutan",
        "Persimmon",
        "Cranberry",
        "Gooseberry",
        "Mulberry",
        "Olive",
        "Tangerine",
        "Mandarin",
        "Kumquat",
        "Quince",
        "Currant",
        "Elderberry",
        "Soursop",
        "Snake Fruit",
        "Custard Apple",
        "Longan",
        "Pomelo",
        "Yuzu",
      ],
    },
    {
      category: "vegetables",
      list: [
        "Carrot",
        "Potato",
        "Tomato",
        "Onion",
        "Broccoli",
        "Spinach",
        "Cucumber",
        "Lettuce",
        "Garlic",
        "Bell Pepper",
        "Mushroom",
        "Zucchini",
        "Corn",
        "Eggplant",
        "Cabbage",
        "Cauliflower",
        "Green Bean",
        "Peas",
        "Celery",
        "Asparagus",
        "Pumpkin",
        "Sweet Potato",
        "Radish",
        "Ginger",
        "Chili Pepper",
        "Kale",
        "Beetroot",
        "Leek",
        "Brussels Sprout",
        "Artichoke",
        "Okra",
        "Turnip",
        "Parsnip",
        "Squash",
        "Bok Choy",
        "Watercress",
        "Arugula",
        "Shallot",
        "Scallion",
        "Yam",
        "Cassava",
        "Taro",
        "Bamboo Shoot",
        "Bitter Melon",
        "Fennel",
        "Kohlrabi",
        "Swiss Chard",
        "Collard Greens",
        "Edamame",
        "Snow Pea",
        "Mustard Greens",
        "Chives",
        "Horseradish",
      ],
    },
    {
      category: "colors",
      list: [
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Orange",
        "Purple",
        "Pink",
        "Black",
        "White",
        "Gray",
        "Brown",
        "Violet",
        "Indigo",
        "Cyan",
        "Magenta",
        "Teal",
        "Turquoise",
        "Lime",
        "Olive",
        "Maroon",
        "Navy",
        "Beige",
        "Cream",
        "Ivory",
        "Silver",
        "Gold",
        "Bronze",
        "Coral",
        "Salmon",
        "Lavender",
        "Lilac",
        "Fuchsia",
        "Crimson",
        "Burgundy",
        "Mustard",
        "Khaki",
        "Mint",
        "Azure",
        "Charcoal",
        "Peach",
        "Amber",
        "Ruby",
        "Emerald",
        "Sapphire",
        "Aquamarine",
        "Periwinkle",
        "Plum",
        "Chocolate",
        "Mauve",
        "Rust",
        "Tan",
        "Copper",
      ],
    },
    {
      category: "animals",
      list: [
        "Dog",
        "Cat",
        "Elephant",
        "Lion",
        "Tiger",
        "Giraffe",
        "Zebra",
        "Monkey",
        "Bear",
        "Horse",
        "Cow",
        "Pig",
        "Sheep",
        "Goat",
        "Chicken",
        "Duck",
        "Rabbit",
        "Mouse",
        "Rat",
        "Hamster",
        "Wolf",
        "Fox",
        "Deer",
        "Kangaroo",
        "Koala",
        "Panda",
        "Crocodile",
        "Alligator",
        "Snake",
        "Lizard",
        "Turtle",
        "Frog",
        "Whale",
        "Dolphin",
        "Shark",
        "Octopus",
        "Jellyfish",
        "Crab",
        "Lobster",
        "Shrimp",
        "Fish",
        "Eagle",
        "Owl",
        "Hawk",
        "Parrot",
        "Penguin",
        "Flamingo",
        "Peacock",
        "Swan",
        "Bat",
        "Butterfly",
        "Bee",
        "Ant",
        "Spider",
        "Scorpion",
        "Mosquito",
        "Fly",
        "Gorilla",
        "Chimpanzee",
        "Hippo",
        "Rhino",
        "Camel",
        "Leopard",
        "Cheetah",
        "Squirrel",
        "Raccoon",
        "Ostrich",
        "Otter",
        "Seal",
        "Walrus",
        "Polar Bear",
        "Platypus",
        "Hedgehog",
        "Buffalo",
        "Bison",
        "Hyena",
      ],
    },
  ],
};
